// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextLevel.AccesoDatos.EF;

#nullable disable

namespace NextLevel.AccesoDatos.Migrations
{
    [DbContext(typeof(NextLevelContext))]
    partial class NextLevelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CursoEstudiante", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.HasKey("CursoId", "EstudianteId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("CursoEstudiante");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.CambioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("NombresArchivos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId")
                        .IsUnique();

                    b.ToTable("CambioRol");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ForoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("ForoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Foro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Foros");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SemanaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoMaterial")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SemanaId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MensajeriaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MensajeriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Mensajeria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EmisorId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("EmisorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Mensajerias");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Semana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Semanas");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Administrador", b =>
                {
                    b.HasBaseType("NextLevel.LogicaNegocio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Docente", b =>
                {
                    b.HasBaseType("NextLevel.LogicaNegocio.Entidades.Usuario");

                    b.Property<int>("NroDocente")
                        .HasColumnType("int")
                        .HasColumnName("NroDocente_NroDeDocente");

                    b.HasDiscriminator().HasValue("Docente");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Estudiante", b =>
                {
                    b.HasBaseType("NextLevel.LogicaNegocio.Entidades.Usuario");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("CursoEstudiante", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.CambioRol", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Estudiante", "Estudiante")
                        .WithOne("CambioRol")
                        .HasForeignKey("NextLevel.LogicaNegocio.Entidades.CambioRol", "EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Curso", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Docente", "Docente")
                        .WithMany("Cursos")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Foro", "Foro")
                        .WithMany()
                        .HasForeignKey("ForoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Foro");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Material", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Semana", null)
                        .WithMany("Materiales")
                        .HasForeignKey("SemanaId");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Mensaje", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Mensajeria", null)
                        .WithMany("Mensajes")
                        .HasForeignKey("MensajeriaId");

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Mensajeria", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Usuario", "Emisor")
                        .WithMany()
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Usuario", "Receptor")
                        .WithMany()
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Semana", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", null)
                        .WithMany("Semanas")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Curso", b =>
                {
                    b.Navigation("Semanas");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Mensajeria", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Semana", b =>
                {
                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Docente", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Estudiante", b =>
                {
                    b.Navigation("CambioRol")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
