// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextLevel.AccesoDatos.EF;

#nullable disable

namespace NextLevel.AccesoDatos.Migrations
{
    [DbContext(typeof(NextLevelContext))]
    partial class NextLevelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CursoEstudiante", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.HasKey("CursoId", "EstudianteId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("CursoEstudiante");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.AltaCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("AltaCursos");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Archivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AltaCursoId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Peso")
                        .HasColumnType("bigint");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AltaCursoId");

                    b.ToTable("Archivo");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("PruebaId")
                        .HasColumnType("int");

                    b.Property<double>("Puntaje")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("PruebaId");

                    b.ToTable("Calificacion");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.CambioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId")
                        .IsUnique();

                    b.ToTable("CambiosDeRol");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Conversacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoConversacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Conversaciones");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calificacion")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dificultad")
                        .HasColumnType("int");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("FechasClases")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ForoId")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("TotalCalificaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("ForoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Foro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.ToTable("Foros");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SemanaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoMaterial")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SemanaId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<double>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.ParticipanteConversacion", b =>
                {
                    b.Property<int>("ConversacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversacionId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ParticipanteConversaciones");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Postulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<int?>("AltaCursoId")
                        .HasColumnType("int");

                    b.Property<int?>("CambioRolId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("AltaCursoId");

                    b.HasIndex("CambioRolId");

                    b.ToTable("Postulaciones");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Prueba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Prueba");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Semana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Semanas");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Temario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Temario");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaVerificado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecuperarCuentaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenVerificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Administrador", b =>
                {
                    b.HasBaseType("NextLevel.LogicaNegocio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Docente", b =>
                {
                    b.HasBaseType("NextLevel.LogicaNegocio.Entidades.Usuario");

                    b.Property<int>("NroDocente")
                        .HasColumnType("int")
                        .HasColumnName("NroDocente_NroDeDocente");

                    b.HasDiscriminator().HasValue("Docente");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Estudiante", b =>
                {
                    b.HasBaseType("NextLevel.LogicaNegocio.Entidades.Usuario");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("CursoEstudiante", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.AltaCurso", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Archivo", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.AltaCurso", null)
                        .WithMany("Archivos")
                        .HasForeignKey("AltaCursoId");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Calificacion", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Prueba", "Prueba")
                        .WithMany("Calificaciones")
                        .HasForeignKey("PruebaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Prueba");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.CambioRol", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Estudiante", "Estudiante")
                        .WithOne("CambioRol")
                        .HasForeignKey("NextLevel.LogicaNegocio.Entidades.CambioRol", "EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Conversacion", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Curso", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Docente", "Docente")
                        .WithMany("Cursos")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Foro", "Foro")
                        .WithMany()
                        .HasForeignKey("ForoId");

                    b.Navigation("Docente");

                    b.Navigation("Foro");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Foro", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Material", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Semana", null)
                        .WithMany("Materiales")
                        .HasForeignKey("SemanaId");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Mensaje", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.ParticipanteConversacion", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Conversacion", "Conversacion")
                        .WithMany("Participantes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Postulacion", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Administrador", "Administrador")
                        .WithMany("Postulaciones")
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.AltaCurso", "AltaCurso")
                        .WithMany()
                        .HasForeignKey("AltaCursoId");

                    b.HasOne("NextLevel.LogicaNegocio.Entidades.CambioRol", "CambioRol")
                        .WithMany()
                        .HasForeignKey("CambioRolId");

                    b.Navigation("Administrador");

                    b.Navigation("AltaCurso");

                    b.Navigation("CambioRol");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Prueba", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", null)
                        .WithMany("Pruebas")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Semana", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", null)
                        .WithMany("Semanas")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Temario", b =>
                {
                    b.HasOne("NextLevel.LogicaNegocio.Entidades.Curso", "Curso")
                        .WithMany("Temarios")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.AltaCurso", b =>
                {
                    b.Navigation("Archivos");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Conversacion", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Curso", b =>
                {
                    b.Navigation("Pruebas");

                    b.Navigation("Semanas");

                    b.Navigation("Temarios");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Prueba", b =>
                {
                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Semana", b =>
                {
                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Administrador", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Docente", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("NextLevel.LogicaNegocio.Entidades.Estudiante", b =>
                {
                    b.Navigation("CambioRol")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
